### ISSUE TITLE
prefix options fields

### ISSUE THREAD

**Issue by aschweigert** [INN/doubleclick-for-wp#52]
Right now we save the plugin options as option_name = `breakpoints` and `network_code` respectively. these should be prefixed with `dfw_` for safety's sake.

Unfortunately it looks like this would require some fairly substantial reworking so opening a ticket for now.

**Comment by aschweigert** [comment]
hm, they ARE prefixed in the master branch but not in the plugin boilerplate branch...the plot thickens.

**Comment by rclations** [comment]
`git blame @rclations`

**Comment by aschweigert** [comment]
ok so i have the rest of the stuff working but this is still a thing that does need to be changed. I tried changing it but found that the options wouldn't save for some reason so need to do some more testing/debugging to try to sort out why exactly.
