### ISSUE TITLE
Ads display on inside pages but not main landing page

### ISSUE THREAD

**Issue by franzoniche** [INN/doubleclick-for-wp#59]
Hi,
The ads have stopped displaying on the front page of my website. The ads inside are still displaying. Can you help?
Thank you

**Comment by rclations** [comment]
hey @franzoniche,

can you provide us with some more information?

If you need to send any sensitive information, you can reach us at support@inn.org

**Comment by franzoniche** [comment]
I submitted an email to support@inn.org for the domain www.rutlandherald.com

**Comment by rclations** [comment]
closing this ticket in favor of the separate INN helpdesk ticket.
