### ISSUE TITLE
various targeting fixes

### ISSUE THREAD

**Issue by dbeniaminov** [INN/doubleclick-for-wp#61]
- allowed posts/pages to be tagged (by changing `is_single` to `is_singular`)
- removed `inurl ` variable from front-page tagging
- modified conditions for `tags ` and `categories ` tagging
- fixed `$this::enqueued ` syntax

**Comment by dbeniaminov** [comment]
[dfw-init.php.zip](https://github.com/INN/doubleclick-for-wp/files/1768268/dfw-init.php.zip)

**Comment by benlk** [comment]
Can you file this as a pull request, please?

**Comment by benlk** [comment]
I'm opening a PR with some of this code, adding you as a co-author, but here's some notes on the changes your file would make:

Changing is_single to is_singular is good. 👍 

Changing is_home to is_front_page is good; we're working to add better support for static homepages across our products. 👍 

I could find no evidence of changed conditionals for tags. ❓ 

Category tagging was removed on static front pages. 👍 

> fixed `$this::enqueued` syntax

I'm not sure what this means; the only change in the code was this:

```
$ git diff | grep enqueued
-		if ( ! $this::$enqueued ) {
+		if(!$this::$enqueued) {
 			$this::$enqueued = true;
```

And that seems to have been part of a general whole-file replacement of the WordPress code standards with a different PHP style, including:

- replacing a number of WordPress functions with their core PHP equivalents,
- removing some function comments,
- removing or altering function docblocks,
- changing variable names,
- generally removing white-space within the file
- adding trailing spaces at the ends of some lines

I'm not commiting those changes, but it's okay, you didn't know that [our house style](https://github.com/INN/docs/blob/700ef0de348f92206471a6454426e4eb1c36838f/style-guides/code/wordpress.md) is [WordPress's coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/). This repo did not have contribution guidelines when you opened this issue, so you wouldn't've been able to know without some deep research on our team. I'll add contribution guidelines soon.

**Comment by benlk** [comment]
Sorry for the notification spam; it took three tries to get GitHub's `Co-authored-by:` syntax correct so that you'd get the credit on that commit. https://help.github.com/articles/creating-a-commit-with-multiple-authors/
