### ISSUE TITLE
Displaying too many options to show / hide in widget -- remove default largo

### ISSUE THREAD

**Issue by 0aveRyan** [INN/doubleclick-for-wp#7]
<img width="393" alt="screen shot 2015-08-05 at 1 27 20 pm" src="https://cloud.githubusercontent.com/assets/9565066/9095488/51946a30-3b6c-11e5-92ea-583bfb666230.png">

Right now the widget presents quite the responsive display conundrum to a user. We should remove the default Largo "hide" options to leave only the DFW options that add classes.

**Comment by benlk** [comment]
Is this still an issue that we'll want to address? The current admin in Largo looks like this: 
<img width="450" alt="screen shot 2016-09-01 at 12 46 47 pm" src="https://cloud.githubusercontent.com/assets/1754187/18176109/4043b3ce-7042-11e6-99e9-31d2c11bab62.png">

**Comment by aschweigert** [comment]
so...this is a largo issue and probably not a plugin issue, would recommend adding a filter in largo that maybe a theme could use to turn off those additional options for certain widgets, etc. 

this issue should probably be closed in favor of an issue to address that over there?

**Comment by benlk** [comment]
Closed in favor of https://github.com/INN/largo/issues/1553.
