### ISSUE TITLE
Weird bug on initial setup

### ISSUE THREAD

**Issue by benlk** [INN/doubleclick-for-wp#8]
When configuring the plugin from a blank slate:
1. fill the blank for the network code 
2. fill the blanks for the breakpoints
3. press Save Changes
4. observe that the network code was saved, but the breakpoints are weirdly misconfigured, as if serialized data was split on colons and then smeared across the boxes. `{` isn't a valid number for a breakpoint pixel count.
5. re-fill the blanks for the breakpoints
6. press Save Changes
7. observe that the network code and the breakpoints are saved correctly.
8. press Save Changes
9. the network code and the breakpoints are still saved correctly.

**Comment by aschweigert** [comment]
yeah, i've noticed this...it will sometimes add two additional breakpoints in the WP admin but once you delete them and save they don't come back.

**Comment by ostkrok** [comment]
We've also encountered the same bug.
@benlk's solution seems to work.
