### ISSUE TITLE
Iframe won't render when the div rendered via ajax (load more data)

### ISSUE THREAD

**Issue by firmanpolyrific** [INN/doubleclick-for-wp#99]
Hello, I have an issue with my ads when it loads from ajax request.
for the first one, it's loaded, but not after that. it just renders **the google_ads_iframe_ div but not the iframe**

I use lazy load method, for ads displaying, is there any issue relating to my issue?

also when i tried to debug using the console, i see the ads that are not rendered are flagged by **Overlay status: Not Displayed**

what does that mean?

**Comment by benlk** [comment]
Hi!

What site are you running ads on? Being able to look at the ad codes output on your page will help us diagnose the problem. If you're not comfortable posting that publicly on this issue, you can send us an email at support@inn.org.

**Comment by firmanpolyrific** [comment]
done @benlk , just sent you an email

**Comment by firmanpolyrific** [comment]
in my case, it's because the google ads were set only for the USA, outside of it, it won't show
